cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<int:product_id>', remove, name='product_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
import shop.views

# from rest_auth.views import (
#     LoginView, LogoutView, PasswordChangeView,
#     PasswordResetView, PasswordResetConfirmView
# )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('users/', include('users.urls')),
    path('search/', include('search.urls')),
    path('', include('shop.urls')),

    # path('login',shop.views.func2)
]
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('accounts/', include('allauth.urls')),
#     path('cart/', include('cart.urls')),
#     # path('coupon/', include('coupon.urls')),
#     # path('order/', include('order.urls')),
#     path('', include('shop.urls')),
# ]

order/urls.py
from django.urls import path
from .views import *

app_name = 'order'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax/', OrderCreateAjaxView.as_view(), name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(), name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(), name='order_validation'),
    path('complete/', order_complete, name='order_complete'),
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
    path('order_list/', order_List.as_view(), name='order_list'),
    path('orderlist2/', OrderitemList.as_view(), name='orderitem_list')
]

order/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from config.settings import AUTH_USER_MODEL
from coupon.models import Coupon
from shop.models import Product

import hashlib

from users.models import User
from .iamport import payments_prepare, find_transaction
from django.db.models.signals import post_save
from django.conf import settings


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=128, verbose_name='이메일')
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    coupon = models.ForeignKey(Coupon, on_delete=models.PROTECT, related_name='order_coupon', null=True, blank=True)
    discount = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100000)])
    username = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE,null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='order_list_products')



    class Meta:
        ordering = ['-created']

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_product(self):
        return sum(item.get_item_price() for item in self.items.all())

    def get_total_price(self):
        total_product = self.get_total_product()
        return total_product - self.discount


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='order_products')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)
    username = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE,null=True, blank=True)


    def __str__(self):
        return '{}'.format(self.id)

    def get_item_price(self):
        return self.price * self.quantity


class OrderTransactionManager(models.Manager):
    def create_new(self, order, amount, success=None, transaction_status=None):
        if not order:
            raise ValueError("주문 오류")
        order_hash = hashlib.sha1(str(order.id).encode('utf-8')).hexdigest()
        email_hash = str(order.email).split("@")[0]
        final_hash = hashlib.sha1((order_hash + email_hash).encode('utf-8')).hexdigest()[:10]
        merchant_order_id = "%s" % final_hash

        payments_prepare(merchant_order_id, amount)

        transaction = self.model(
            order=order,
            merchant_order_id=merchant_order_id,
            amount=amount
        )

        if success is not None:
            transaction.success = success
            transaction.transaction_status = transaction_status

        try:
            transaction.save()
        except Exception as e:
            print("save error", e)

        return transaction.merchant_order_id

    def get_transaction(self, merchant_order_id):
        result = find_transaction(merchant_order_id)
        if result['status'] == 'paid':
            return result
        else:
            return None


class OrderTransaction(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    merchant_order_id = models.CharField(max_length=120, null=True, blank=True)
    transaction_id = models.CharField(max_length=120, null=True, blank=True)
    amount = models.PositiveIntegerField(default=0)
    transaction_status = models.CharField(max_length=220, null=True, blank=True)
    type = models.CharField(max_length=120, blank=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    objects = OrderTransactionManager()

    def __str__(self):
        return str(self.order.id)

    class Meta:
        ordering = ['-created']


def order_payment_validation(sender, instance, created, *args, **kwargs):
    if instance.transaction_id:
        import_transaction = OrderTransaction.objects.get_transaction(merchant_order_id=instance.merchant_order_id)

        merchant_order_id = import_transaction['merchant_order_id']
        imp_id = import_transaction['imp_id']
        amount = import_transaction['amount']

        local_transaction = OrderTransaction.objects.filter(merchant_order_id=merchant_order_id,
                                                            transaction_id=imp_id,
                                                            amount=amount
                                                            ).exists()

        if not import_transaction or not local_transaction:
            raise ValueError("비정상 거래입니다.")


# 결제 정보가 생성된 후에 호출할 함수를 연결해준다.
post_save.connect(order_payment_validation, sender=OrderTransaction)

order/forms.py
from django import forms
from .models import Order



class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']
        # widgets = {'product' : forms.HiddenInput}

        
    def __init__(self, *args, **kwargs):
        super(OrderCreateForm, self).__init__(*args, **kwargs)
    #
        # self.fields['product'].initial = 'default value'
    #
        # self.fields['product'].disabled = True

order/views.py
from django.db import transaction
from django.shortcuts import render, get_object_or_404
from .models import *
from cart.cart import Cart
from .forms import *
from django.views.generic.base import View
from django.http import JsonResponse
from django.contrib.admin.views.decorators import staff_member_required
# pdf를 위한 임포트
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.views.generic import ListView
from .models import Order

from django.contrib.auth.models import User
# import weasyprint
from users.models import User
from shop.models import Product



def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)

            # order.user = request.user
            # order.product = request.product
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.amount
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity']
                                         )
            cart.clear()
            return render(request, 'order/created_test.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'order/create_test.html', {'cart': cart, 'form': form})


def order_complete(request):
    order_id = request.GET.get('order_id')
    order = Order.objects.get(id=order_id)
    return render(request, 'order/complete.html', {'order': order})


class OrderCreateAjaxView(View,Product):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated": False}, status=403)
        product = Product.objects.all()
        cart = Cart(request)
        for item in cart:
            print(item)
            product_name = item['product']
            product_quantity = item['quantity']
        form = OrderCreateForm(request.POST)
        # print(form)
        # 실패목록
        # print(request.GET.all('cart'))
        # print(cart.session['products'])
        # session_key = cart.session.session_key
        # print(session_key)
        # print(request.session.get('cart'))   = None
        # print(Cart) = <class 'cart.cart.Cart'>
        # print(cart['product']) = TypeError: 'Cart' object is not subscriptable
        # cart['product']의 형태가 아니라 cart.product 이런식으로 안해서 일어나는 오류
        # print(cart.products) = AttributeError: 'Cart' object has no attribute 'products'
        print("post 통과")



        if form.is_valid():
            with transaction.atomic():
                print("is_valid 통과")


                order = form.save(commit=False)
                print("form save 통과")
                # print(request.user.u_nickname)
                if cart.coupon:
                    order.coupon = cart.coupon
                    order.discount = cart.coupon.amount
                # order.username = request.user.u_nickname
                # print(User.objects.get(u_nickname=request.user.u_nickname))
                order.username = User.objects.get(u_nickname=request.user.u_nickname)
                print('오더프로덕트전')
                order.product = Product.objects.get(p_name=product_name)
                print(order.product)
                # order.product = Product.objects.get(name=Product.name)
                # print(order.product)
                # 새로운 오류
                # order.product = Product.name = ValueError: Cannot assign "<django.db.models.query_utils.DeferredAttribute object at 0x000002080E84ED60>": "Order.product" must be a "Product" instance.
                # order.product = Product.objects.get(id=form.product_id)
                # order.product = request.session.product
                # print(order.product)
                order.save()


                prod = Product.objects.get(p_name=product_name)
                prod.stock -= int(product_quantity)
                prod.save()


                # print('product:',order.product)
                print("order save 1 통과")
                # order.save()
                # print(cart[1])
                for item in cart:

                    # 프랑스라고 출력은 되는데 그럼 cart안에도 있는게 아닌가?
                    OrderItem.objects.create(order=order,
                                             product=item['product'],
                                             price=item['price'],
                                             quantity=item['quantity']
                                             )


                cart.clear()
                data = {
                    "order_id": order.id
                }
                return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)


class OrderCheckoutAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated": False}, status=403)

        order_id = request.POST.get('order_id')
        order = Order.objects.get(id=order_id)
        amount = request.POST.get('amount')

        try:
            merchant_order_id = OrderTransaction.objects.create_new(
                order=order,
                amount=amount
            )
        except:
            merchant_order_id = None

        if merchant_order_id is not None:
            data = {
                "works": True,
                "merchant_id": merchant_order_id
            }
            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)


class OrderImpAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated": False}, status=403)

        order_id = request.POST.get('order_id')
        order = Order.objects.get(id=order_id)
        merchant_id = request.POST.get('merchant_id')
        imp_id = request.POST.get('imp_id')
        amount = request.POST.get('amount')

        try:
            trans = OrderTransaction.objects.get(
                order=order,
                merchant_order_id=merchant_id,
                amount=amount
            )
        except:
            trans = None

        if trans is not None:
            trans.transaction_id = imp_id
            trans.success = True
            trans.save()
            order.paid = True
            order.save()

            data = {
                "works": True
            }

            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'order/admin/detail.html', {'order': order})


@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('order/admin/pdf.html', {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename=order_{}.pdf'.format(order.id)
    # weasyprint.HTML(string=html).write_pdf(response, stylesheets=[weasyprint.CSS(settings.STATICFILES_DIRS[0]+'/css/pdf.css')])
    return response



# 주문내역 조회




# 왜인지 모르지만 구매자 목록
# 후에 buyer detailfh tnwjdgodigka
class order_List(ListView):
    model = Order
    template_name = 'order_list.html'
    context_object_name = 'order_list'


    def get_queryset(self, **kwargs):

        print(self.request.user.id)
        queryset = Order.objects.filter(username=self.request.user.id)
        return queryset

# 주문내역 조회 다시 도전

class OrderitemList(ListView):
    model = OrderItem
    template_name = 'orderitem_list.html'
    context_object_name = 'orderitem_list'

    # def get_queryset(self, **kwargs):
    #     user = self.request.session.get('user')
    #     print(user)
    # #
    #     queryset = OrderItem.objects.filter(email=self.request.session.get('user'))
    #     return queryset

order/templates/order/complete.html
{% extends 'base.html' %}

{% block title %}
Order Complete
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="alert alert-success" role="alert">Thank you!<br/>
            Your order has been successfully completed.<br/>
        Your order number is <strong>{{order.id}}</strong></div>

    </div>
</div>
{% endblock %}

order/templates/order/create.html
{% extends 'base.html' %}

{% block title %}
Checkout
{% endblock %}

{% block script %}
<script type="text/javascript">
csrf_token = "{{ csrf_token }}";
order_create_url = "{% url 'order:order_create_ajax' %}";
order_checkout_url = "{% url 'order:order_checkout' %}";
order_validation_url = "{% url 'order:order_validation' %}";
order_complete_url = "{% url 'order:order_complete' %}";
</script>

<script src="https://cdn.iamport.kr/js/iamport.payment-1.1.5.js" type="text/javascript"></script>

{% load static %}
<script src="{% static 'js/checkout.js' %}" type="text/javascript"></script>

{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="alert alert-info" role="alert">Your Order</div>
        <ul class="list-group">
        {% for item in cart %}
            <li class="list-group-item">
                {{item.quantity}}X{{item.product.name}}
                <span>{{item.total_price}}</span>
            </li>

        {% if cart.coupon %}
            <li class="list-group-item">
                "{{ cart.coupon.code }}" ({{ cart.coupon.amount }} off)
                <span>- ${{ cart.get_total_discount|floatformat:"2" }}</span>
            </li>
        {% endif %}
        </ul>
        <div class="alert alert-success" role="alert">Total : {{cart.get_total_price|floatformat:"2"}}</div>

        <!-- form에 class 추가 -->
        <form action="" method="post" class="order-form">
            {{form.as_p}}
            {% csrf_token %}

<!--{{user.id}}-->
<!--            &lt;!&ndash; hidden field 추가&ndash;&gt;-->
<!--            <h3 class="join_title"><h5>체크해주세요</h5></h3>-->
<!--            <input type="checkbox" name="username_id" value={user.id} style="zoom:2.0;">-->
            <input type="hidden" name="pre_order_id" value="0">
            <input type="hidden" name="amount" value="{{ cart.get_total_price|floatformat:'2' }}">
            <input type="submit" class="btn btn-primary float-right" value="Place Order">

        </form>

        {% endfor %}
        <script>
            var product = document.getElementById('{{ form.product.id_for_label }}')
    product.value = navigator.product;
  	// Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

        </script>
    </div>
</div>
{% endblock %}

order/templates/order/create_test.html
{% extends 'base.html' %}

{% block title %}
Checkout
{% endblock %}

{% block script %}
<script type="text/javascript">
csrf_token = "{{ csrf_token }}";
order_create_url = "{% url 'order:order_create_ajax' %}";
order_checkout_url = "{% url 'order:order_checkout' %}";
order_validation_url = "{% url 'order:order_validation' %}";
order_complete_url = "{% url 'order:order_complete' %}";
</script>

<script src="https://cdn.iamport.kr/js/iamport.payment-1.1.5.js" type="text/javascript"></script>

{% load static %}
<script src="{% static 'js/checkout.js' %}" type="text/javascript"></script>

{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="alert alert-info" role="alert">Your Order</div>
        <ul class="list-group">
        {% for item in cart %}
            <li class="list-group-item">
                {{item.quantity}}X{{item.product.name}}
                <span>{{item.total_price}}</span>
            </li>
        {% endfor %}
        {% if cart.coupon %}
            <li class="list-group-item">
                "{{ cart.coupon.code }}" ({{ cart.coupon.amount }} off)
                <span>- ${{ cart.get_total_discount|floatformat:"2" }}</span>
            </li>
        {% endif %}
        </ul>
        <div class="alert alert-success" role="alert">Total : {{cart.get_total_price|floatformat:"2"}}</div>

        <!-- form에 class 추가 -->

        <form action="" method="post" class="order-form">
<!--            <div><span id = "username" >-->
<!--                        내 닉네임 :  {{ user.u_nickname }}</span></div>-->
<!--            <div>-->
<!--                {% for item in cart %}-->
<!--         <span id = "product_id" >-->
<!--                        상품명 :  {{ item.product }}</span>-->

<!--        {% endfor %}-->
<!--            </div>-->
            {{form.as_p}}
            {% csrf_token %}




<!--{{user.id}}-->
<!--            &lt;!&ndash; hidden field 추가&ndash;&gt;-->
<!--            <h3 class="join_title"><h5>체크해주세요</h5></h3>-->
<!--            <input type="checkbox" name="username_id" value={user.id} style="zoom:2.0;">-->
            <input type="hidden" name="pre_order_id" value="0">
            <input type="hidden" name="amount" value="{{ cart.get_total_price|floatformat:'2' }}">
            <input type="submit" class="btn btn-primary float-right" value="Place Order">


        </form>
    </div>
</div>
{% endblock %}

order/templates/order/order_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Signup" %}{% endblock %}
{% load humanize%}
{% block content %}

<h1>{{ user.u_nickname }} 님의 주문 내역입니다.</h1>

<div class="row mt-5">
    <div class="col-12">
        <table class="table table-light">
            <thead class="thead-light">
            <tr>
                <th scope="col">판매자</th>
                <th scope="col">상품명</th>
                <th scope="col">구매할때입력한 firts+last</th>
                <th scope="col">구매닉네임</th>
                <th scope="col">email</th>
                <th scope="col">주문날짜</th>
            </tr>
            </thead>
            <tbody class="text-dark">
            {% for order in order_list %}

            {% if order.paid == 1%}
<!--            {% with product=item.product %}-->
            <tr>

                <th>{{order.product.writer.u_nickname}}</th>


                <th>{{order.product}}</th>
                <th>{{order.first_name}}{{order.last_name}}</th>
                <th>{{order.username.u_nickname}}</th>
                <th>{{order.email}}</th>
                <th>{{order.updated|date:'Y-m-d H:i'}}</th>
            </tr>
<!--            {% endwith %}-->
            {% endif %}

            {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}

order/templates/order/orderitem_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Signup" %}{% endblock %}
{% load humanize%}
{% block content %}

<h1>{{ user.u_nickname }} 님의 주문 내역입니다.</h1>

<!--<hr>-->
<!--<h3>내 주문 정보</h3>-->
<!--<table class="table table-striped">-->
<!--    <thead>-->
<!--    <tr>-->
<!--        <th scope="col">Image</th>-->
<!--        <th scope="col">Product</th>-->
<!--        <th scope="col">Price</th>-->
<!--        <th scope="col">주문날짜</th>-->
<!--    </tr>-->
<!--    </thead>-->
<!--    <tbody>-->
<!--    {% for order in order_list %}-->
<!--    {% with product=item.product %}-->
<!--    <tr>-->
<!--        <th scope="row">-->
<!--            <a href="{{ product.get_absolute_url }}">-->
<!--                <img src="{{ product.image.url }}" class="img-thumbnail">-->
<!--            </a>-->
<!--        </th>-->
<!--        <th>{{order.product}}</th>-->
<!--        <th>{{order.price}}</th>-->
<!--        <th>{{order.register_date|date:'Y-m-d H:i'}}</th>-->

<!--    </tr>-->
<!--    {% endwith %}-->
<!--    {% endfor %}-->

<!--    </tbody>-->
<!--</table>-->
<div class="row mt-5">
    <div class="col-12">
        <table class="table table-light">
            <thead class="thead-light">
            <tr>
                <th scope="col">오더</th>
                <th scope="col">상품명</th>

                <th scope="col">price</th>
                <th scope="col">주문날짜</th>
            </tr>
            </thead>
            <tbody class="text-dark">
            {% for orderitem in orderitem_list %}

             {% with product=orderitem.product %}
            <tr>
                <th scope="row">{{orderitem.order_id}}</th>

                <th href="{{ product.get_absolute_url }}">{{orderitem.product}}</th>
                <th>{{orderitem.price}}</th>
                <th>{{orderitem.created}}</th>
            </tr>
            {% endwith %}

            {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}