cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<int:product_id>', remove, name='product_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
import shop.views

# from rest_auth.views import (
#     LoginView, LogoutView, PasswordChangeView,
#     PasswordResetView, PasswordResetConfirmView
# )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('users/', include('users.urls')),
    path('search/', include('search.urls')),
    path('', include('shop.urls')),

    # path('login',shop.views.func2)
]
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('accounts/', include('allauth.urls')),
#     path('cart/', include('cart.urls')),
#     # path('coupon/', include('coupon.urls')),
#     # path('order/', include('order.urls')),
#     path('', include('shop.urls')),
# ]

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_in_category_test, name='product_all'),
    path('create_product/', create_product, name='create_product'),
    path('<category_slug>/', product_in_category_test, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
    path('inquiry/create/<int:id>/', inquiry_create, name='inquiry_create'),
    path('inquiry/delete/<int:id>/', inquiry_delete, name='inquiry_delete'),
    path('register_product/<int:id>/', register_product, name='register_product'),
    path('delete_product/<int:id>/', delete_product, name='delete_product'),
]

#
# urlpatterns = [
#     path('', product_in_category, name='product_all'),
#     path('/create_product', create_product, name='create_product'),
#     path('<slug:category_slug>/', product_in_category, name='product_in_category'),
#     path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
#     path('<int:id>/inquiry_create/', inquiry_create, name='inquiry_create'),
#     path('<int:id>/inquiry_create/<int:inquiry_id>/delete/', inquiry_create, name='inquiry_create'),
#     # path('register_product/<int:product_id>/', register_product, name='register_product'),
# ]

shop/models.py
from django.db import models
from django.urls import reverse
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill

from config.settings import AUTH_USER_MODEL
from users.models import User
from django.conf import settings
from django.utils.text import slugify


class Category(models.Model):
    c_name = models.CharField(max_length=200, db_index=True)
    c_slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)

    class Meata:
        ordering = ['c_name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.c_name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.c_slug])

    def get_absolute_url2(self):
        return reverse('shop:product_in_category', args=[self.c_slug])



class Type(models.Model):
    t_name = models.CharField(max_length=100)

    class Meta:
        db_table = 'types'

    def __str__(self):
        return self.t_name

class Product(models.Model):
    writer = models.ForeignKey(AUTH_USER_MODEL,on_delete=models.CASCADE, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')
    type = models.ForeignKey(Type, on_delete=models.CASCADE, null=True)
    p_name = models.CharField(max_length=200, db_index=True)
    p_slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True, null=True, blank=True)
    addr = models.TextField(blank=True)
    content = models.TextField(blank=True)
    address1 = models.CharField("Address line 1", max_length=300)
    address2 = models.CharField("Address line 2", max_length=300)
    price = models.DecimalField(max_digits=8, decimal_places=0, null=True)
    stock = models.IntegerField(default=1)
    size = models.ForeignKey('Size', on_delete=models.CASCADE, null=True)
    facility1 = models.BooleanField('Facility1', null=True, blank=True, default=False)
    facility2 = models.BooleanField('Facility2', null=True, blank=True, default=False)
    facility3 = models.BooleanField('Facility3', null=True, blank=True, default=False)
    facility4 = models.BooleanField('Facility4', null=True, blank=True, default=False)
    facility5 = models.BooleanField('Facility5', null=True, blank=True, default=False)
    rule1 = models.BooleanField('Rule1', null=True, blank=True, default=False)
    rule2 = models.BooleanField('Rule2', null=True, blank=True, default=False)
    rule3 = models.BooleanField('Rule3', null=True, blank=True, default=False)
    safety1 = models.BooleanField('Safety1', null=True, blank=True, default=False)
    safety2 = models.BooleanField('Safety2', null=True, blank=True, default=False)
    safety3 = models.BooleanField('Safety3', null=True, blank=True, default=False)
    display = models.BooleanField('Display', default=True)
    order = models.BooleanField('Order', default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, null=True, blank=True)
    checkin = models.DateTimeField(null=True, blank=True)
    checkout = models.DateTimeField(null=True, blank=True)

    class Meata:
        ordering = ['-created']
        index_together = [['id','p_slug']]

    def __str__(self):
        return self.p_name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.p_slug])


def path_image_path(instance, filename):
    #{instance.content} => {instance.product.content}
    return f'products/{instance.product.content}/{filename}'

class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    file = ProcessedImageField(upload_to='products/%Y/%m/%d', null=False, processors=[ResizeToFill(120, 100)], format='JPEG', options={'quality':90})

class Inquiry(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=150)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

class Size(models.Model):
    z_name = models.CharField(max_length=100)

    class Meta:
        db_table = 'sizes'

    def __str__(self):
        return self.z_name

class ProductSizes(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    size     = models.ForeignKey('Size', on_delete=models.CASCADE)

    class Meta:
        db_table = 'product_sizes'

shop/forms.py
from django import forms
from .models import *
from django import forms
from django.urls import reverse_lazy
from .widgets import DatePickerWidget


from django import forms
from django.forms import ModelForm

from .models import Product


class DateInput(forms.DateInput):
    input_type = 'date'


class PromiseForm(ModelForm):

    class Meta:
        model = Product
        fields = ['writer', 'p_name', 'checkin', 'checkout']
        widgets = {
            'checkin': DatePickerWidget,
            'checkout': DatePickerWidget,
        }



class checkinForm(forms.ModelForm):
    class Meta:
        model = Product
        widgets = {
            'checkin': DatePickerWidget,
            'checkout': DatePickerWidget,
        }
        exclude = ()

from bootstrap_datepicker_plus.widgets import DatePickerInput

from django import forms



class ProductForm(forms.ModelForm):
    class Meta:
        model = Product  # 사용할 모델
        fields = '__all__'
        widgets = {
            'checkin': forms.DateInput(attrs={'type':'date'}),  # default date-format %m/%d/%Y will be used
            'checkout': forms.DateInput(attrs={'type':'date'}),  # specify date-frmat
        }
        exclude = ()

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['file',]

ImageFormSet = forms.inlineformset_factory(Product, Image, form=ImageForm, extra=5)

class RegisterProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ()

class TypeForm(forms.ModelForm):
    class Meta:
        model = Type
        exclude = ()

class SizeForm(forms.ModelForm):
    class Meta:
        model = Size
        exclude = ()

class InquiryForm(forms.ModelForm):
    class Meta:
        model = Inquiry
        exclude = ('product', 'user',)

shop/views.py
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from cart.forms import AddProductForm
from .forms import *
from django.db import transaction
from django.http import HttpResponseNotAllowed
from django.core.paginator import Paginator
from django.views.generic.edit import CreateView
from django.views.generic import ListView
#
from allauth.account.signals import user_signed_up
from django.dispatch import receiver


def func2(abcde) :
    return render(abcde, 'templates/users01/login.html')









def product_in_category(request, category_slug=None):
    current_category = None
    categories = Category.objects.all()
    products = Product.objects.filter(display=True)

    paginator = Paginator(products,4)
    page = request.GET.get('page')
    posts=paginator.get_page(page)


    if category_slug:
        current_category = get_object_or_404(Category, c_slug=category_slug)
        products = products.filter(category=current_category)


    return render(request, 'shop/list.html', {'current_category': current_category,
                                              'categories': categories,
                                              'products': products,

                                              })


def product_in_category_test(request, category_slug=None):
    current_category = None
    categories = Category.objects.all()
    products = Product.objects.filter(display=True)

    paginator = Paginator(products,4)
    page = int(request.GET.get('page',1))
    posts=paginator.get_page(page)


    if category_slug:
        current_category = get_object_or_404(Category, c_slug=category_slug)
        products = products.filter(category=current_category)
        paginator = Paginator(products, 3)
        page = int(request.GET.get('page',1))
        posts = paginator.get_page(page)


    return render(request, 'shop/list_test.html', {'current_category': current_category,
                                              'categories': categories,
                                              'products': products,
                                              'posts' : posts
                                              })








def product_detail(request, id, product_slug=None):
    product = get_object_or_404(Product, id=id, p_slug=product_slug)
    add_to_cart = AddProductForm(initial={'quantity': 1})
    return render(request, 'shop/detail.html', {'product': product, 'add_to_cart': add_to_cart})


    # login_session = request.session.get('login_session', '')
    # context = {'login_session':login_session}
    #
    # product = get_object_or_404(Product, id=id, slug=product_slug)
    # context['product'] = product
    # inquiry = get_object_or_404(Inquiry, id=id)
    # context['inquiry'] = inquiry
    # if product.writer.user_id == login_session:
    #     context['writer'] = True
    # else :
    #     context['writer'] = False


#
# @receiver(user_signed_up)
# def user_signed_up_(**kwargs):
#     user = kwargs['user']
#     extra_data = user.socialaccount_set.filter(provider='naver')[0].extra_data
#     user.last_name = extra_data['name'][0:4]
#     user.first_name = extra_data['name'][4:]
#     user.save()
# from django.shortcuts import render

# Create your views here.




class PromiseCreateView(CreateView):
    model = Product
    form_class = PromiseForm






@login_required
def create_product(request) :
    if request.method == 'POST':
        product_form = ProductForm(request.POST)
        image_formset = ImageFormSet(request.POST, request.FILES)
        print('체크인')
        print(product_form)
        if product_form.is_valid() and image_formset.is_valid():
            print('valid통과')
            product = product_form.save(commit=False)
            product.writer = request.user
            with transaction.atomic():
                product.save()
                image_formset.instance = product
                image_formset.save()
                return redirect(product)
    else:

        product_form = ProductForm()
        image_formset = ImageFormSet()

    context = {'product_form' : product_form, 'image_formset' : image_formset}
    return render(request, 'shop/create_product.html', context)

@login_required
def register_product(request, id):
    product = get_object_or_404(Product, pk=id)
    if product.writer == request.user or request.user.is_staff == '1':
        if request.method == "GET":
            form = ProductForm(instance=product)
            image_formset = ImageFormSet()
            return render(request, 'shop/register_product.html', {'form': form, 'image_formset':image_formset})
        else:
            form = RegisterProductForm(request.POST, instance=product)
            image_formset = ImageFormSet(request.POST, request.FILES)
            print('POST~!', form)
            if form.is_valid():
                print('valid~!')
                product.category = form.cleaned_data['category']
                product.type = form.cleaned_data['type']
                product.p_name = form.cleaned_data['p_name']
                product.p_slug = form.cleaned_data['p_slug']
                product.addr = form.cleaned_data['addr']
                product.content = form.cleaned_data['content']
                product.price = form.cleaned_data['price']
                product.address1 = form.cleaned_data['address1']
                product.address2 = form.cleaned_data['address2']
                product.stock = form.cleaned_data['stock']
                product.size = form.cleaned_data['size']
                product.facility1 = form.cleaned_data['facility1']
                product.facility2 = form.cleaned_data['facility2']
                product.facility3 = form.cleaned_data['facility3']
                product.facility4 = form.cleaned_data['facility4']
                product.facility5 = form.cleaned_data['facility5']
                product.rule1 = form.cleaned_data['rule1']
                product.rule2 = form.cleaned_data['rule2']
                product.rule3 = form.cleaned_data['rule3']
                product.safety1 = form.cleaned_data['safety1']
                product.safety2 = form.cleaned_data['safety2']
                product.safety3 = form.cleaned_data['safety3']
                product.display = form.cleaned_data['display']
                product.order = form.cleaned_data['order']
                product.updated = timezone.now()
                with transaction.atomic():
                    product.save()
                    image_formset.instance = product
                    image_formset.save()
                    print(product)
                    return redirect('shop:product_all')
    else :
        messages.error(request, "내 게시글이 아닙니다.")
        return redirect(product)
    return redirect('shop:product_all')

@login_required
def delete_product(request, id) :
    product = get_object_or_404(Product, pk=id)
    if product.writer == request.user or request.user.is_staff == '1':
        product = get_object_or_404(Product, pk=id)
        product.delete()
        return redirect('shop:product_all')
    else :
        messages.error(request, "내 게시글이 아닙니다.")
        return redirect(product)

@login_required
def inquiry_create(request, id):
    product = get_object_or_404(Product, pk=id)
    if request.method == "POST":
        form = InquiryForm(request.POST)
        if form.is_valid():
            inquiry = form.save(commit=False)
            inquiry.user = request.user
            inquiry.product = product
            inquiry.save()
            return redirect(product)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'product': product, 'form': form}
    return render(request, 'shop/detail.html', context)

@login_required
def inquiry_delete(request, id) :
    inquiry = get_object_or_404(Inquiry, id=id)
    product = get_object_or_404(Product, id=inquiry.product.id)
    if inquiry.user == request.user or request.user.is_staff == '1':
        inquiry.delete()
        return redirect(product)
    else :
        messages.error(request, "내 문의글이 아닙니다.")
        return redirect(product)

shop/templates/shop/detail.html
{% extends 'base.html' %}
{% block title %}Product Detail{% endblock %}
{% load static %}
{% block content %}

<div class="container my-3" xmlns="http://www.w3.org/1999/html">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ product.subject }}</h2>

    <div class="container">
        <div class="row">

            <div class="col-4">
                {% for image in product.image_set.all %}
                <img src="{{image.file.url}}" width="100%" alt="Product Image">
                {% endfor %}
            </div>
            <div class="col">
                <h1 class="btn btn-outline-info btn-block btn-lg">'{{product.category}}'</h1>
                <h1 class="display-6">{{product.p_name}}</h1>
                <h3 class="display-6">Host : {{product.writer}}</h3>
                <h5><span class="badge badge-secondary">&nbsp가&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp격&nbsp</span> &#8361;{{product.price}}</h5>
                <h5><span class="badge badge-secondary">숙소형태</span> {{product.type}}</h5>
                <h5><span class="badge badge-secondary">&nbsp위&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp치&nbsp</span> {{product.address1}}{{product.address2}}</h5>
                <h5><span class="badge badge-secondary">보유수량</span> {{product.stock}}</h5>
                <h5><span class="badge badge-secondary">침대유형</span> {{product.size}}</h5>
                <h5><span class="badge badge-secondary" style="border-bottom-width: 10px;padding-bottom: 3.75;margin-bottom: 10px;">숙소소개</span> {{product.content|linebreaks}}</h5>
                <div style="border: 2px solid #788884; max-height: 35px; max-width: 100px; margin:5px; padding-top: 2px;" ><h4 >숙소시설</h4></div>
                <div style="margin:10px">
                    {% if product.facility1 is True %}
                    <img src="https://onlineshop-jj.s3.ap-northeast-2.amazonaws.com/static/images/cooking.png">
                    {% endif %}&nbsp
                    {% if product.facility2 is True %}
                    <img src="https://onlineshop-jj.s3.ap-northeast-2.amazonaws.com/static/images/terrace.png">
                    {% endif %}&nbsp
                    {% if product.facility3 is True %}
                    <img src="https://onlineshop-jj.s3.ap-northeast-2.amazonaws.com/static/images/barbecue.png">
                    {% endif %}&nbsp
                    {% if product.facility4 is True %}
                    <img src="https://onlineshop-jj.s3.ap-northeast-2.amazonaws.com/static/images/refrigerator.png">
                    {% endif %}&nbsp
                    {% if product.facility5 is True %}
                    <img src="https://onlineshop-jj.s3.ap-northeast-2.amazonaws.com/static/images/air_conditioning.png">
                    {% endif %}</div><br>

                <div style="border: 2px solid #788884; max-height: 35px; max-width: 100px; margin:5px; padding-top: 2px;" ><h4>금지사항</h4></div>
                <div style="margin:10px">
                    {% if product.rule1 is True %}
                    <img src="https://onlineshop-jj.s3.ap-northeast-2.amazonaws.com/static/images/nosmoking.png">
                    {% endif %}&nbsp
                    {% if product.rule2 is True %}
                    <img src="https://onlineshop-jj.s3.ap-northeast-2.amazonaws.com/static/images/no-pets.png">
                    {% endif %}&nbsp
                    {% if product.rule3 is True %}
                    <img src="https://onlineshop-jj.s3.ap-northeast-2.amazonaws.com/static/images/no_cook.png">
                    {% endif %}</div><br>

                <div style="border: 2px solid #788884; max-height: 35px; max-width: 100px; margin:5px; padding-top: 2px;" ><h4>안전설비</h4></div>
                <div style="margin:10px">
                    {% if product.safety1 is True %}
                    <img src="https://onlineshop-jj.s3.ap-northeast-2.amazonaws.com/static/images/co.png">
                    {% endif %}&nbsp
                    {% if product.safety2 is True %}
                    <img src="https://onlineshop-jj.s3.ap-northeast-2.amazonaws.com/static/images/flame.png">
                    {% endif %}&nbsp
                    {% if product.safety3 is True %}
                    <img src="https://onlineshop-jj.s3.ap-northeast-2.amazonaws.com/static/images/fireex.png">
                    {% endif %}</div>
                <form action="{% url 'cart:product_add' product.id %}" method="post">
                    {{add_to_cart}}
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary btn-sm" value="장바구니">
                </form>

                <form action="{% url 'shop:delete_product' product.id %}" method="get">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-secondary btn-sm float-right" value="삭 제"></form>
                <form action="{% url 'shop:register_product' product.id %}" method="get">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-secondary btn-sm float-right" value="수 정"></form>

            </div>

            <div data-viewid="findway" data-root="" class="cont_findway">
                <center><span id="em4" class="tit_subject btn btn-outline-primary btn-block">찾아가는 길</span></center>
                <div class="findway_map">
                    <section class="module map only-desktop">

                        <div class="map-container" tabindex="0"
                             style="position: relative; overflow: hidden; background: url(&quot;https://ssl.pstatic.net/static/maps/mantle/1x/pattern_1.png&quot;) 0px 0px repeat transparent;">
                            <div id="map" style="width:810px;height:380px;"></div>
                            <div id="product_address1" data-title="{{ product.p_name }}" data-address="{{ product.address1 }}" style="display:none">{{ product.address1 }}</div>

                            <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=e69641dcc68fbf07541f339e0ba36f35&libraries=services" ></script>
                            <script>

var mapContainer = document.getElementById('map'), // 지도를 표시할 div
    mapOption = {
        center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
        level: 5 // 지도의 확대 레벨
    };

var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

// HTML5의 geolocation으로 사용할 수 있는지 확인합니다
if (navigator.geolocation) {

    // GeoLocation을 이용해서 접속 위치를 얻어옵니다
    navigator.geolocation.getCurrentPosition(function(position) {

        var lat = position.coords.latitude, // 위도
            lon = position.coords.longitude; // 경도

        var locPosition = new kakao.maps.LatLng(lat, lon), // 마커가 표시될 위치를 geolocation으로 얻어온 좌표로 생성합니다
            message = '<div style="padding:8px;">현 위치</div>'; // 인포윈도우에 표시될 내용입니다

        // 마커와 인포윈도우를 표시합니다
        displayMarker(locPosition, message);

      });

} else { // HTML5의 GeoLocation을 사용할 수 없을때 마커 표시 위치와 인포윈도우 내용을 설정합니다

    var locPosition = new kakao.maps.LatLng(33.450701, 126.570667),
        message = 'geolocation을 사용할수 없어요..'

    displayMarker(locPosition, message);
}

// 지도에 마커와 인포윈도우를 표시하는 함수입니다
function displayMarker(locPosition, message) {

    // 마커를 생성합니다
    var marker = new kakao.maps.Marker({
        map: map,
        position: locPosition
    });

    var iwContent = message, // 인포윈도우에 표시할 내용
        iwRemoveable = true;

    // 인포윈도우를 생성합니다
    var infowindow = new kakao.maps.InfoWindow({
        content : iwContent,
        removable : iwRemoveable
    });

    // 인포윈도우를 마커위에 표시합니다
    infowindow.open(map, marker);

    // 지도 중심좌표를 접속위치로 변경합니다
    map.setCenter(locPosition);
}
                        </script>
                        </div>
                    </section><br><br><br><br>
                    <h5 style="padding-left: 15px;padding-bottom: 10px;">{{ product.inquiry_set.count }}개의 문의가 있습니다.</h5>
                    <div>
                        <ul>
                            {% for inquiry in product.inquiry_set.all %}
                            <li style="border: 3px solid #788884; height: 80px; width: 800px; margin:5px">
                                <div class=" btn-light" style="max-height: 35px; width: 500px; margin:5px;border-top-width: 100px;padding-top: ‒10;padding-top: 10px;padding-left: 10px;">{{ inquiry.content }}</div>
                            </li>
                            <form action="{% url 'shop:inquiry_delete' inquiry.id %}" method ="post">
                                {% csrf_token %}
                                <input type="submit" class="float-right" value="Delete" style="margin-top: -30px;margin-right: 10px;">
                            </form>
                            <div class="badge badge-light float-right" style="border: 2px solid #788884; max-height: 27px; max-width: 500px; margin-top:-80px; margin-right:10px"><h6>작성자 : {{ inquiry.user }}</h6>
                            </div>
                            <div class="badge float-right" style=" max-height: 27px; max-width: 500px; margin-top:-53px; margin-right:10px"><h8>{{ inquiry.create_date }}</h8>
                            </div>
                            {% endfor %}
                        </ul>
                    </div>
                    <form action="{% url 'shop:inquiry_create' product.id %}" method="post" class="my-3">
                        {% csrf_token %}
                        <div class="form-group">
                            <center><div class="btn btn-info btn-block ">문의</div></center>
                            <textarea name="content" id="content" class="form-control btn btn-outline-primary" rows="5"></textarea>
                        </div>

                        <input type="submit" value="문의 하기" class="btn btn-primary float-right">

                    </form>
                </div><br><br><br>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop/templates/shop/list.html
{% extends 'base.html' %}
{% block title %}AirBnB Main{% endblock %}
{% block content %}



  <form action="./" method="post">
      Date: <input autocomplete="off" type="text" id="datepicker" name="formdate" />
      {% csrf_token %}
      <input type="submit" value="검색" />
    </form>
<div class="row">
    <div class="col-2">
        <div class="list-group">
            <a href="/" class="list-group-item {% if not current_category %}active{% endif %} btn btn-primary btn-block" >All</a>
            {% for c in categories %}

            <a href="{{c.get_absolute_url2}}"
               class="list-group-item {% if current_category.c_slug == c.c_slug %}active{% endif %} btn btn-primary btn-block"style="background-color: #008DC9;">{{c.c_name}}</a>
            {% endfor %}
        </div>
    </div>
    <div class="col">
        <div class="alert alert-info" role="alert">
            {% if current_category %}{{current_category.c_name}}{% else %}All Products{% endif %}
        </div>
        <div class="row">
            {% for product in products %}
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    <div id="product_{{ product.id }}" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                    {% for image in product.image_set.all %}
                    <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                        <img src="{{ image.file.url }}" class="card-img-top"
                             alt="{{ image.file.image }}">
                    </div>
                    {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#product_{{ product.id }}"
                           role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#product_{{ product.id }}"
                           role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{product.p_name}}</h5>
                        <h5 class="card-user">{{product.writer}}</h5>
                        <p class="card-text">{{product.addr}} <span class="badge badge-secondary">&#8361;{{product.price}}</span>
                        </p>
                        <a href="{{product.get_absolute_url}}" class="btn btn-primary btn-block">View Detail</a>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>


</div>

{% endblock %}

shop/templates/shop/mylist.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Signup" %}{% endblock %}
{% load humanize%}
{% block content %}

<h1>{{ user.u_nickname }} 님의 상품 내역입니다.</h1>



<div class="row mt-5">
    <div class="col-12">
        <table class="table table-light">
            <thead class="thead-light">
            <tr>

                <th scope="col">상품명</th>
                <th scope="col">가격</th>
                <th scope="col">재고</th>

            </tr>
            </thead>
            <tbody class="text-dark">
            {% if products %}
            {% for product in products %}
            {{product.writer}}
<!--            {% if product.writer == user.u_nickname %}-->

            <tr>
                <th>{{product.name}}</th>
                <th>{{product.price}}</th>
                <th>{{product.stock}}</th>
            </tr>

<!--            {% endif %}-->

            {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}