cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<int:product_id>', remove, name='product_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
import shop.views

# from rest_auth.views import (
#     LoginView, LogoutView, PasswordChangeView,
#     PasswordResetView, PasswordResetConfirmView
# )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('users/', include('users.urls')),
    path('search/', include('search.urls')),
    path('', include('shop.urls')),

    # path('login',shop.views.func2)
]
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('accounts/', include('allauth.urls')),
#     path('cart/', include('cart.urls')),
#     # path('coupon/', include('coupon.urls')),
#     # path('order/', include('order.urls')),
#     path('', include('shop.urls')),
# ]

order/urls.py
from django.urls import path
from .views import *

app_name = 'order'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax/', OrderCreateAjaxView.as_view(), name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(), name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(), name='order_validation'),
    path('complete/', order_complete, name='order_complete'),
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
    path('order_list/', order_List.as_view(), name='order_list'),
    path('orderlist2/', OrderitemList.as_view(), name='orderitem_list')
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('<int:pk>/', userprofile, name='userprofile'),
    # path('user_modify/', user_modify, name='user_modify'),
    path('host_main/', host_main, name='host_main'),
    path('<int:pk>/modify/', user_modify, name='user_modify'),
    path('user_delete/', user_delete, name='user_delete'),
    path('change_password/', change_password, name='change_password'),
    # path('/create_product', create_product, name='create_product'),
    # path('<slug:category_slug>/', product_in_category, name='product_in_category'),
    # path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
]

users/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser


# class CustomUser(AbstractUser):
#     phone = models.CharField(
#         max_length=100
#     )
#
#     # 회원 가입 시 이메일 입력을 필수로 한다.
#     REQUIRED_FIELDS = ["email"]

class User(AbstractUser):
    u_nickname = models.CharField(max_length=200, verbose_name='닉네임')  # user 닉네임
    u_phonenum = models.CharField(max_length=200, verbose_name='전화번호', null=True)  # user 전화번호
    u_address = models.CharField(max_length=200, verbose_name='주소', null=True)  # user 주소
    SEX = (('F', '여자'), ('M', '남자'), ('U', '선택 안함'))
    u_sex = models.CharField(max_length=10, choices=SEX, null=True, unique=False)
    email = models.EmailField(max_length=128, verbose_name='사용자이메일')

users/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['u_nickname','email',"u_phonenum", 'u_address','u_sex']


class SignupForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["u_nickname","email", "u_phonenum", 'u_address','u_sex']



    def signup(self, request, user):
        user.u_nickname = self.cleaned_data['u_nickname']
        user.u_phonenum = self.cleaned_data['u_phonenum']
        user.u_address = self.cleaned_data['u_address']
        user.u_sex = self.cleaned_data['u_sex']
        user.email = self.cleaned_data['email']
        user.save()

users/views.py
from django.shortcuts import render

import json

from django.contrib import auth
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm
# from django.contrib.auth.models import User
from users.models import User
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
import requests
from django.contrib.auth.forms import UserChangeForm

from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from users.forms import SignupForm
from django.contrib import messages, auth
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from .forms import CustomUserChangeForm
from django.contrib.auth.hashers import check_password

# Create your views here.
# def userprofile(requeset):
#     return render (requeset, 'users/profile.html')
# # def user_modify(requeset):
#     # return render (requeset, 'users/modify.html')

def userprofile(request, pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=pk)
    context = {
        'user': user
    }
    return render(request, 'users/profile.html', context)


# @login_required
# def user_modify(request):
#     if request.method == 'POST':
#         user_form = UpdateUserForm(request.POST, instance=request.user)
#         profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user)
#
#         if user_form.is_valid() and profile_form.is_valid():
#             user_form.save()
#             profile_form.save()
#             messages.success(request, 'Your profile is updated successfully')
#             return redirect('users/profile.html')
#     else:
#         user_form = UpdateUserForm(instance=request.user)
#         profile_form = UpdateProfileForm(instance=request.user)
#     return render(request, 'users/modify.html', {'user_form': user_form, 'profile_form': profile_form})
#

@login_required
def user_modify(request,pk):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            # return redirect('/user/<int:pk>/')
        return render(request, 'users/profile.html')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
        'pk' : pk
    }
    print('fail')
    return render(request, 'users/modify.html', context)

@login_required
def user_delete(request):
    if request.method == 'POST':
        pw_del = request.POST["pw_del"]
        user = request.user

        if check_password(pw_del, user.password):
            user.delete()
            print('완료')
            return redirect('/')

    return render(request, 'users/delete.html')

@login_required
def change_password(request):
    context= {}
    if request.method == "POST":
        current_password = request.POST.get("origin_password")
        user = request.user
        if check_password(current_password,user.password):
            new_password = request.POST.get("password1")
            password_confirm = request.POST.get("password2")
            if new_password == password_confirm:
                user.set_password(new_password)
                user.save()

                return render(request, 'users/profile.html')
            else:
                context.update({'error':"새로운 비밀번호를 다시 확인해주세요."})
    else:
        context.update({'error':"현재 비밀번호가 일치하지 않습니다."})


    return render(request, 'users/changepassword.html',context)



def host_main(requeset):
    return render (requeset, 'airbnb/hostmain_test.html')

templates/users/changepassword.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Signup" %}{% endblock %}
{% block content %}


<div class="container" xmlns="http://www.w3.org/1999/html">
    <div class="login_container">

        <div class="login_title">
            <h1>Change Password</h1>
        </div>
        <form method="POST" action="" class="login_form">
            {% csrf_token %}
            </br>
            <div class="login_input_container">
                <div class="username_form_text">Origin Password</div>
                <div class="input_container">
                    <input class="login_input" name="origin_password" type="password">
                </div>

                <div class="password_form_text"> New Password</div>
                <div class="input_container">
                    <input class="login_input" name="password1" type="password">
                </div>
                <div class="confirm_password_form_text">Confirm Password</div>
                <div class="input_container">
                    <input class="login_input" name="password2" type="password">
                </div>
            </div>
            <div class="login_btn_container">
                <input type="submit" class="login_btn" value="Submit">
            </div>

    </form>
</div>
</div>

{% endblock %}

templates/users/delete.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Signup" %}{% endblock %}


{% block content %}
<h1>{{ user.u_nickname }} 님 여기는 회원 탈퇴페이지 입니다.</h1>
<h2> 버튼을 누르면 탈퇴가 완료됩니다</h2>

        <form action="{% url 'users:user_delete' %}" method="POST">
            {% csrf_token %}
           비밀번호 : <input type="text" name="pw_del">
            <button class="btn btn-primary">회원탈퇴</button>

        </form>


{% endblock %}

templates/users/modify.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Signup" %}{% endblock %}


{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <div class="join_row">
        <h3 class="join_title"><h2>닉네임</h2></h3>
        <input type="text" id="u_nickname" name="u_nickname" value="" maxlength="16" required=""
               PLACEHOLDER= '현재 닉네임은  {{ user.u_nickname }} 입니다'
               style="width:300px;height:50x;font-size:20px;">
    </div>

    <div class="join_row">
        <h3 class="join_title"><h2>주소</h2></h3>

        <input type="text" id="u_address" name="u_address" value="" maxlength="500" required="" PLACEHOLDER={{ user.u_address }}
               style="width:500px;height:500x;font-size:20px;">
    </div>
    <div class="join_row">
        <h3 class="join_title"><h2>email</h2></h3>
        <input type="text" name="email" value="" data-email="" size="30" required=""
               fld_esssential="" option="regEmail" label="이메일"
               placeholder={{ user.email }}
               style="width:300px;height:30px;font-size:20px;">
    </div>
    <div class="join_row join_phonenum">
        <h3 class="join_title"><h2>핸드폰번호</h2></h3>
        <div class="phonenum">
            <input type="text" name="u_phonenum" id="u_phonenum" pattern="[0-9]*"
                   value="" label="핸드폰번호" size="11" maxlength="11"
                   placeholder={{ user.u_phonenum }}
                   style="width:500px;height:500x;font-size:20px;">
            <span class="bar"></span>
        </div>
    </div>
    <div class="join_row join_sex">
        <h3 class="join_title"><h2>성별</h2></h3>
        <div class="ps_box gender_code">
            <select name="u_sex" aria-label="u_sex" style="width:100px;height:30px;font-size:20px;">
                <option value="" selected="">성별</option>
                <option value="M">남자</option>
                <option value="F">여자</option>
                <option value="U">선택 안함</option>
            </select>
        </div>
    </div>

    <button class="btn btn-primary">수정</button>
</form>

{% endblock %}

templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Signup" %}{% endblock %}
{% load humanize%}
{% block content %}

<h1>{{ user.u_nickname }} 님 환영합니다</h1>
{% if request.user == user %}

<h2>
    회원정보 관련
</h2>
<button class="btn btn-secondary" onclick="location.href='{% url 'users:user_modify' user.pk %}'"> 회원정보 수정</button>

<button class="btn btn-secondary" onclick="location.href='{% url 'users:user_delete' %}'"> 회원 탈퇴</button>

<button class="btn btn-secondary" onclick="location.href='{% url 'users:change_password' %}'"> 비밀번호 변경</button>
{% endif %}
<hr>
<h2> 내 상품 내역 </h2>
<button class="btn btn-secondary" onclick="location.href='{% url 'order:order_list' %}'"> 내 주문 내역(완성)</button>
<button class="btn btn-secondary" onclick="location.href='{% url 'order:orderitem_list' %}'"> 내 주문 내역</button>


{% endblock %}